### ISSUE TITLE
__dirname fails to resolve package.json on build

### ISSUE THREAD

**Issue by nmcclay** [dgeb/ember-cli-addon-guard#18]
Testing this with an application using ember-engines 0.7.1, and ember 3.10 I encountered this error during build:

```
Cannot find module '/Users/me/git/my-app/node_modules/ember-cli-addon-guard/lib/utils/package.json'
```

Investigating this error led me to these 3 lines that rely on `__dirname`. 

https://github.com/dgeb/ember-cli-addon-guard/blob/736d0f3be9c54dc432a63c6af1bde190d0d9c4f1/lib/utils/namespace-templates.ts#L8

https://github.com/dgeb/ember-cli-addon-guard/blob/736d0f3be9c54dc432a63c6af1bde190d0d9c4f1/lib/plugins/namespace-addon-in-templates-babel.ts#L60

https://github.com/dgeb/ember-cli-addon-guard/blob/4a0559a28236dbd82cb5d5802b0e73fb0b7b5421/lib/plugins/namespace-addon-imports-babel.ts#L55

Replacing `__dirname` with a hard path to the root ember-cli-addon-guard directory resolves this issue.

**Comment by dgeb** [comment]
@nmcclay I think I need to be able to follow your debugging logic more closely, and how you ended up being led to `__dirname` as the source of your problem. I added those `baseDir` methods to enable babel caching, as per some direction from @rwjblue.

Are you able to publish a public reproduction? I have a demo app here that perhaps you could start with: https://github.com/dgeb/ember-cli-addon-guard-namespacing-demo

**Comment by nmcclay** [comment]
Yep, I'll see if I can get you a clear repo case to reference.

**Comment by nmcclay** [comment]
Hey @dgeb I spent some time attempting to reproduce this issue but ultimately it seems like it was related to other dependencies on my side since updating my apps seemed to fix it. Closing issue, sorry for the confusion on my part.

**Comment by dgeb** [comment]
@nmcclay Thanks for the update! Glad you were able to resolve the issue on your end.
