### ISSUE TITLE
Guard against old versions of `calculate-cache-key-for-tree`

### ISSUE THREAD

**Issue by dgeb** [dgeb/ember-cli-addon-guard#4]
The duplication-checking algorithm in ember-cli-addon-guard should probably rely on each addon's `cacheKeyForTree` function rather than its version.

The vast majority of ember addons rely on the `calculate-cache-key-for-tree` package to implement `cacheKeyForTree`. As per https://github.com/ember-cli/calculate-cache-key-for-tree/pull/14 there can be a problem with versions of this addon < 1.2. When reading `cacheKeyForTree` we should guard against the old algorithm, and use the new one instead. However, we should defer to any custom algorithms provided by an addon.

Perhaps the simplest answer here is to patch ember-cli to rely on the new 1.2 version of `calculate-cache-key-for-tree`, and bring that patch back to all actively supported versions of ember-cli (which has `calculate-cache-key-for-tree` as a dependency).

A more rigorous but expensive solution could actually check if the old algorithm is in use for each addon and then flag it as a problem. This seems a bit heavy-handed as a pre-build step though.

@rwjblue @stefanpenner thoughts?

**Comment by rwjblue** [comment]
I think it would be fine to backport to a release version of ember-cli, however I think _largely_ this just isn't "our problem". 

Normal dependency drift allows for the fix from https://github.com/ember-cli/calculate-cache-key-for-tree/pull/14, I think it would probably be enough protection to have ember-cli-addon-guard warn if it detects a `calculate-cache-key-for-tree < 1.2`.
